# Generated by Django 4.2.5 on 2023-09-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
