# Generated by Django 4.2.5 on 2023-10-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_taxon_display_name_alter_taxon_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnum', models.CharField(max_length=200)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.taxon')),
            ],
        ),
    ]
