# Generated by Django 4.2.5 on 2023-10-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.location'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='accnum',
            field=models.CharField(max_length=200, unique=True, verbose_name='Accession number'),
        ),
    ]
