# Generated by Django 4.2.5 on 2023-10-11 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_accession_location_alter_accession_accnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='collected',
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
        migrations.AddField(
            model_name='accession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='status',
            field=models.CharField(choices=[('c', 'Current'), ('d', 'Non-current due to death'), ('t', 'Non-current due to transfer'), ('s', 'Stored in dormant state'), ('o', 'Other')], default='o', max_length=1),
        ),
    ]
