# Generated by Django 4.2.5 on 2023-10-11 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_accession_collected_accession_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='collected',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
